blank_issues_enabled: true
contact_links:
  - name: Security Vulnerability Report
    url: https://github.com/octofelickz/dependabot-reachability-analysis/security/advisories/new
    about: Please report security vulnerabilities through GitHub's security advisory feature