name: Reachability Analysis
description: Perform vulnerability exposure analysis to help understand priority of remediation
title: "Reachability Analysis: [VULNERABILITY_NAME]"
labels: ['reachability-analysis', 'security']
assignees:
  - felickz
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this query request! 
        
        CodeQL queries help identify security vulnerabilities, bugs, and quality issues in PHP code. Providing detailed information will help us create effective queries that address real-world needs.

  - type: textarea
    id: alert
    attributes:
      label: Dependabot Alert Link
      description: "Please provide a link to the dependabot alert"
      placeholder: "https://github.com/octofelickz/dependabot-reachability-analysis/security/dependabot/1"
      value: ""
    validations:
      required: true

